### ISSUE TITLE
ShuttleSet: some inconsistent labeling

### ISSUE THREAD

**Issue by Va6lue** [wywyWang/CoachAI-Projects#12]
Video ID: 9, 10.
Their shot type labels don't match the corresponding videos.

**Comment by wywyWang** [comment]
Thanks for your interest in our work. Could you specify which shots your were referring to?

**Comment by Va6lue** [comment]
Every shots in the video 9, 10 are wrong. I guess you put the wrong csv files or wrong links with them.

You can easily find the problems by checking the first shot you listed in the csv file and the time position of the video corresponding to it.

**Comment by wywyWang** [comment]
Thank you for pointing out this to us! I would suggest skipping the two matches directly for your use.
