### ISSUE TITLE
Cannot find video source for Match ID 12 (NG_Ka_Long_Angus_SHI_Yu_Qi_Thailand_Masters_2020_SemiFinals)

### ISSUE THREAD

**Issue by tim-forrer** [wywyWang/CoachAI-Projects#2]
It seems that there is no longer an official BWF video source for match ID 12 in the ShuttleSet dataset.

How I have tried to search it:
- Look within the [BWF playlist for the Thailand Masters 2020](https://www.youtube.com/playlist?list=PLA7ZcagI0frCnbXjAD_EQPYOPXQrqao3L)
- Try a general search on Youtube
- Try a general search on Google

I'm aware that BWF sometimes imposes regional restrictions due to rights limitations however as this dataset was compiled by researchers in Taiwan I'm assuming that all videos should be available in Taiwan.

Are the owners of ShuttleSet aware of a working link to this match?

Going forward it might be helpful to include links to the videos as part of [match.csv](https://github.com/wywyWang/CoachAI-Projects/blob/main/ShuttleSet/set/match.csv) to help other users of the dataset find the source videos more quickly.

I would be happy to open a PR to add this if desired as I have sourced all the video links apart from this one.

**Comment by wywyWang** [comment]
Hi,

Thanks for your interest! It indeed is better to include the video link in the match.csv. Please feel free to open a PR and I will handle and merge this suggestion. Thanks for your help.

**Comment by tim-forrer** [comment]
The PR is opened (#3)

Feel free to add the missing link if you have it
