### ISSUE TITLE
Where are Video links of ShuttleSet22?

### ISSUE THREAD

**Issue by botamochi6277** [wywyWang/CoachAI-Projects#4]
I cannot find YouTube links and video ids of ShuttleSet22.
Can you tell me the links?

**Comment by wywyWang** [comment]
Thanks for your interest in our project! We do not intend to provide links, but the videos of these matches can be easily found on the Internet. Hope this helps.

**Comment by botamochi6277** [comment]
OK, I will try to search. Thank you for replying.
