### ISSUE TITLE
About Movement Forecasting Dataset

### ISSUE THREAD

**Issue by good-demo** [wywyWang/CoachAI-Projects#5]
Thank you for sharing your work
I try to rerun the code(Where Will Players Move Next? Dynamic Graphs and Hierarchical Fusion for Movement Forecasting in Badminton (AAAI 2023)), but I can't find the dataset link.

**Comment by good-demo** [comment]
python train.py --preprocessed_data_path demo.csv  

Traceback (most recent call last):
  File "train.py", line 212, in <module>
    main()
  File "train.py", line 203, in main
    train_loss, train_loss_location, train_loss_type = train(train_dataloader, valid_dataloader, encoder, decoder, location_criterion, shot_type_criterion, encoder_optimizer, decoder_optimizer, args, device=device)
ValueError: too many values to unpack (expected 3)

**Comment by wywyWang** [comment]
Hi,

Thank you for your interest! You can find the dataset in the [ShuttleSet repo](https://github.com/wywyWang/CoachAI-Projects/tree/main/ShuttleSet). Hope this helps.

**Comment by good-demo** [comment]
Thanks for your reply
When I use badmintoncleaner.py creat dataset  


codes_type, uniques_type = pd.factorize(matches['type'])
TypeError: 'BadmintonCleaner' object is not subscriptable


python train.py --preprocessed_data_path demo.csv

Traceback (most recent call last):
File "train.py", line 212, in
main()
File "train.py", line 203, in main
train_loss, train_loss_location, train_loss_type = train(train_dataloader, valid_dataloader, encoder, decoder, location_criterion, shot_type_criterion, encoder_optimizer, decoder_optimizer, args, device=device)
ValueError: too many values to unpack (expected 3)

**Comment by good-demo** [comment]
Thanks for your reply
