### ISSUE TITLE
About creating user's model

### ISSUE THREAD

**Issue by qiuboxiang** [wywyWang/CoachAI-Projects#6]
Thank you so much for your work!

When I was trying to rerun the CoachAI project,I met some problem about the usage.I don't know how to create my own model and get the .pth file that is needed in run_CoachAI.py

Could you make a brief and little more specific introduction about creating my own model and the step of running a demo of the CoachAI Project?

Thank you so much for that!

**Comment by wywyWang** [comment]
Hi,

Thanks for your interest. Could you please specify which project you are referring to? We have 8 projects under this repo. Thanks!

**Comment by qiuboxiang** [comment]
Thank you for your immediate reply!

I’m referring to the usage in CoachAI Badminton Environment.

Thank for your patience again!

**Comment by wywyWang** [comment]
I am not sure what specific problems you encountered, but please follow the readme in CoachAI Badminton Environment.

In terms of training a model, you can run `./train.py --preprocessed_data_path demo.csv`.

**Comment by qiuboxiang** [comment]
Sorry for my inaccurate description before.After I  trained ShuttleNet, DyMF and BC models following readme,the second step require me to prepare my own model to be trained.That’s where I started to confused.

**Comment by good-demo** [comment]
Looking forward to your detailed document explanation.
python generate_nogui.py it will be error
Traceback (most recent call last):
  File "c:/Users/xxxxxxxx/Desktop/CoachAI Badminton Environment/generate_nogui.py", line 326, in <module>
    eps_clip, has_continuous_action_space=True, train_step=max_rally_count/2)
TypeError: __init__() got an unexpected keyword argument 'has_continuous_action_space'

**Comment by wywyWang** [comment]
Hi @qiuboxiang ,

As the environment aims to provide an RL badminton environment, the meaning of *prepare your own model* is that you can customize/propose a method (e.g., PPO) to optimize and evaluate based on the realistic environment consisting of ShuttleNet and DyMF. You can use BC as your own model to test the results swiftly.

The details of the paper will be released in a month depending on the process of AAAI preview.

**Comment by wywyWang** [comment]
Hi @good-demo ,

I didn't get the step where you encountered this. Could you please specify which step you are referring to and what you have finished?

**Comment by good-demo** [comment]
I didn't use demo.csv; instead, I utilized a dataset created by badmintoncleaner.py.
I finished MovementForecasting/train.py, which created config, encoder, and decoder.
StrokeForecasting/train.py also completed successfully, generating config, encoder, and decoder.
Finally, First2Ball/train.py finished and produced ShuttleDyMFNet2ball-final.pt
（The K-fold experiment only generated results for one fold by default.）
How should I proceed with the second step? 
![1705665596360](https://github.com/wywyWang/CoachAI-Projects/assets/90243359/f6c2f117-7f7a-4daf-b7cb-a8d9672bbca8)
![1705665636403](https://github.com/wywyWang/CoachAI-Projects/assets/90243359/e178fc8a-d80a-42fc-b2b0-351c40535d58)
How can I obtain the file continuous_subjective.csv?

**Comment by good-demo** [comment]
I created continuous_subjective.csv by Utils
![1705734086369](https://github.com/wywyWang/CoachAI-Projects/assets/90243359/5701f216-8f0e-42e4-b236-b6de28f74bea)

but error 
![1705734165713](https://github.com/wywyWang/CoachAI-Projects/assets/90243359/1177a80e-b256-4ddb-9f8c-c5a5095129e2)
