### ISSUE TITLE
Can i use this to detect actions of badminton in live mathc?

### ISSUE THREAD

**Issue by Shekharmeena28** [wywyWang/CoachAI-Projects#8]
My doubt is can i use this to detect events like points, rally and deuce and game points in a live badminton match, if it is possible how can i implement it

**Comment by wywyWang** [comment]
Hello,

Thank you for your interest in our work! I believe our project can be used to detect points with our virtual empire algorithm, but it requires data from videos if you would like to utilize it in real-time games. You can check [the visualization repo](https://github.com/wywyWang/CoachAI-Projects/tree/main/Visualization%20Platform/preprocessing) for more details.

**Comment by Shekharmeena28** [comment]
hi wei-yao, i hope you are doing well, as i was asking for live match
inference, there would be streaming url for the live badminton match will
this work for that as live match does not have the csv file its just the
video
