### ISSUE TITLE
Annotation tool not available anymore?

### ISSUE THREAD

**Issue by alexeyev** [wywyWang/CoachAI-Projects#9]
Dear colleagues,

thank you for your great work.

Is the annotation tool you have used for shuttlecock tracking data labeling publicly available? The link on hackermd doesn't work (404).

Thanks in advance, best regards,
Anton Alekseev.

**Comment by wywyWang** [comment]
Hi,

Thanks for your interest in our work. Unfortunately, we cannot provide the labeling tool. This is not released publicly, but we provide the labeling details in the [ShuttleSet](https://dl.acm.org/doi/10.1145/3580305.3599906) paper.

Please feel free to contact me if you have any questions.

**Comment by alexeyev** [comment]
> Unfortunately, we cannot provide the labeling tool.

Such a pity. Yet thanks for the reply and the pointers!
